name: capstone_project
dependencies:
  - python==3.6.5
  - numpy
  - pandas
  - matplotlib
  - nb_conda
  - pip:
    - scipy
    - scikit-learn
    - torch==0.4.1
    - torchvision
    - "git+https://github.com/szagoruyko/pytorchviz"
